name: Node.js CI

on:
  pull_request:
    branches:
      - master

jobs:
  pr-check:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
      - name: Install dependencies
        run: npm install